# Creates the bamboo agent user and group, and its associated folders

- block:
  - name: '[BAMBOOAGENT] Group "{{ bambooagent_group }}"'
    group: name={{ bambooagent_group }} state=present
    when: ansible_os_family!="Windows"

  - name: '[BAMBOOAGENT] Group "{{ bambooagent_group }}"'
    win_group: name={{ bambooagent_group }} state=present
    when: ansible_os_family=="Windows"

#
# Creates the user Ubuntu
- block:

  # this is a bit particular to my own setup as the bambooagent is an LDAP user
  # but we still want the agent to have a home folder
  - getent:
      database: passwd
      key: "{{ bambooagent_user }}"
      split: ':'
      fail_key: no
    register: check_bambooagent
    
  - name: '[BAMBOOAGENT] Set variable for user existence'
    set_fact:
      no_user: "{{ getent_passwd[bambooagent_user]==None }}"
      
  - debug: var=check_bambooagent
      
  - debug: var=no_user
  
  - name: '[BAMBOOAGENT] Ensuring home of "{{ bambooagent_user }}" exists (2)'
    file:
      path: "{{ getent_passwd[bambooagent_user][4] }}"
      state: directory
      owner: "{{ bambooagent_user }}"
      group: "{{ bambooagent_group }}"
    when: not no_user

  - name: '[BAMBOOAGENT] Creating non-existing user "{{ bambooagent_user }}"'
    user:
      name: "{{ bambooagent_user }}"
      comment: "Bamboo agent"
      state: present
      group: "{{ bambooagent_group }}"
      createhome: yes
    when: no_user
  
  - name: '[BAMBOOAGENT] Ensuring root folder of the bamboo agent exists'
    file:
      path: "{{ bambooagent_install_root }}"
      state: directory
      owner: "{{ bambooagent_user }}"
      group: "{{ bambooagent_group }}"
    when: no_user
 
  when: ansible_distribution=="Ubuntu"


#
# Creates the user / OSX
- block:

  # this is a bit particular to my own setup as the bambooagent is an LDAP user
  # but we still want the agent to have a home folder
  - name: '[BAMBOOAGENT] Creating non-existing user "{{ bambooagent_user }} - OSX"'
    user:
      name: "{{ bambooagent_user }}"
      comment: "Bamboo agent"
      state: present
      group: "{{ bambooagent_group }}"
      createhome: yes
      
  when: ansible_distribution=="MacOSX"

#
# Creates the user / windows
- block:

  - name: '[BAMBOOAGENT][WIN] create user "{{ bambooagent_user }}"'
    win_user:
      name: "{{ bambooagent_user }}"
      fullname: "Bamboo agent user"
      user_cannot_change_password: yes
      password_never_expires: yes
      state: present
      password: "{{bambooagent_passwd}}"
      groups: 
      - "{{ bambooagent_group }}"
    register: win_bamboo_user_reg

  # because this user will be running the service
  - name: '[BAMBOOAGENT][WIN] add account to Log on as a service'
    win_user_right:
      name: SeServiceLogonRight
      users:
      - "{{ bambooagent_user }}"
      action: add

  # because we may want to log in and create a home folder (temporary directory, etc)
  - name: '[BAMBOOAGENT][WIN] add account to Log on as a user'
    win_user_right:
      name: SeInteractiveLogonRight
      users:
      - "{{ bambooagent_user }}"
      action: add      

  - name: '[BAMBOOAGENT][WIN] whoami to create the home folder'
    win_shell: "whoami"
    become: yes
    become_user: "{{ bambooagent_user }}"
    become_method: runas
    vars:
    - ansible_become_password: "{{bambooagent_passwd}}"

  - debug:
      var: win_bamboo_user_reg
      
  - name: '[BAMBOOAGENT][WIN] create user "{{ bambooagent_user }}" home'
    win_file:
      path: "{{ bambooagent_install_root }}"
      state: directory

  when: ansible_os_family=="Windows"
  vars:
    - bambooagent_passwd: "{{ lookup('password', 'windows/' + inventory_hostname + '/bambooagent length=15') }}"
  
#
# hides the bamboo agent from the login screen
#

- name: Hides the user from the login screen OSX
  command: defaults write /Library/Preferences/com.apple.loginwindow HiddenUsersList -array-add "{{ bambooagent_user }}"
  when: ansible_distribution=="MacOSX"

- name: Creates the login hidding file
  file:
    path: "/var/lib/AccountsService/users/{{ bambooagent_user }}"
    state: touch
    owner: root
    group: root
    mode: "u+rw,g+r,o+r"
  when: ansible_distribution=="Ubuntu"

- name: Hides the user from the login screen Ubuntu
  ini_file:
    dest=/var/lib/AccountsService/users/{{ bambooagent_user }}
    section=User
    option=SystemAccount
    value=true
    backup=yes
  when: ansible_distribution=="Ubuntu"


#
# do not let the Bamboo agent to modify its home folder
#
- name: "Prevents the bamboo agent to modify its home folder / non-ubuntu (disabled)"
  file:
    path: "{{ bambooagent_install_root }}"
    state: directory
    owner: "{{ bambooagent_user }}"
    group: "{{ bambooagent_group }}"
    mode: "u+rx,g+rx"
  when: ((check_bambooagent is failed) or (ansible_distribution!="Ubuntu")) and False

- name: "Prevents the bamboo agent to modify its home folder / ubuntu (disabled)"
  file:
    path: "{{ getent_passwd[bambooagent_user][4] }}"
    state: directory
    owner: "{{ bambooagent_user }}"
    group: "{{ bambooagent_group }}"
    mode: "u+rx,g+rx"
  when: ((check_bambooagent is succeeded) and (ansible_distribution=="Ubuntu")) and False
