#
# Checking that required variables are set
#

- name: '[BAMBOO] Checking that required variables are set'
  fail:
    msg: "{{ item }} is not defined"
  when: item is undefined
  loop:
    - bambooagent_user
    - bambooagent_group
    - bamboo_server_url
    - bambooagent_install_root
    - bambooagent_service_name
    - bambooagent_version
    - bambooagent_agent_root
    - bambooagent_capability_file
    - bambooagent_jar_filename
    - bambooagent_jar_filename_full_path
  tags:
    - always
