---

# This file configures the bamboo agent

- include_tasks: check_vars.yml
  tags:
    - bambooagent:checks
    - checks

- include_tasks: bambooagent_create_user.yml
  tags:
    - bambooagent:installation

# Installs the certificates, if any, on the system
- include_tasks: bambooagent_install_system_certificate.yml
  tags:
    - bambooagent:installation
  when: (certificate_files is defined) and (certificate_files is not empty)

- include_tasks: bambooagent_install_starter.yml
  tags:
    - bambooagent:installation

- include_tasks: bambooagent_configure_capabilities.yml
  tag:
    - bambooagent:configuration
   
